### PR TITLE
Bank Segmentation

### LINKED ISSUE #262: 💡[FEATURE]: Bank Customer Segmentation: KMeans, HAC & DBScan
**Context**

Financial institutions have diverse customers with different background, income levels etc. In order to formulate an effective marketing strategy, the financial institution would need to identify different segments of its customer portfolio and have a targeted approach to its customers based on their profile. This analysis would focus on clustering the financial institutions customers for the purposes of developing an optimum marketing strategy. The performance of the models will be evaluated based on its ability to clearly define the different customer segments in the dataset.

### PR DESCRIPTION
**Pull request by adityasingh-0803**
I have added readme file, bank segmentation file using k means clustering DBSCAN of various banks data .csv file

## 🛠️ Related Issue
Enhancement in bank segmentation using K means DBSCAN done via Jupyter notebook

- Closes #262 

## 📝 Description
Evaluate the quality of clusters using internal metrics (e.g., silhouette score) or external metrics if ground truth labels are available.
Compare the results of K-means and DBSCAN to see which algorithm provides better insights for your specific task.

## 🔍 Type of PR

- [ ] 🐛 Bug fix
- [X] ✨ Feature enhancement
- [X] 📚 Documentation update
- [ ] 🛑 Other (specify): _______________

## 📸 Screenshots / 🎥 Videos (if applicable)
Screenshot 2024-06-13 131938
Screenshot 2024-06-13 131921
Screenshot 2024-06-13 131901
Screenshot 2024-06-13 131838
Screenshot 2024-06-13 131805

## ✅ Checklist

- [ X] I have performed a self-review of my code.
- [ X] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have commented my code, particularly in hard-to-understand areas.

## ℹ️ Additional Context
This will gave the better visualisation and enhancement in clustering will be present

### CODE REVIEW

**Review by Akshat111111 — COMMENTED** [review]
Kindly put your file inside bank bankrupt detection

**Comment by adityasingh-0803** [comment]
So I have to delete this and again PR to be created?

**Comment by adityasingh-0803** [comment]
If you will merge the pr kindly add label to it so that leaderboard fetch the points thanks

**Comment by adityasingh-0803** [comment]
@Akshat111111 I have done the work kindly check

**Review by Akshat111111 — COMMENTED** [review]
yeah, it works

**Comment by Akshat111111** [comment]
why you are disturbing the main readme, create a new pr

**Comment by adityasingh-0803** [comment]
Ok I will not add Readme file should I create new pr?

**Comment by Akshat111111** [comment]
inside bankrupty folder

**Pull request merged**
