### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AKSHITHA-CHILUKA**
## 🛠️ Related Issue

- Closes #[#676]

## 📝 Description

[Provide a concise description of the changes. Include the purpose and any relevant context or details.]

## 🔍 Type of PR

- [ ] 🐛 Bug fix
- [x] ✨ Feature enhancement
- [x] 📚 Documentation update
- [ ] 🛑 Other (specify): _______________

## 📸 Screenshots / 🎥 Videos (if applicable)

[Attach screenshots or videos]

## ✅ Checklist

- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## ℹ️ Additional Context

[Include any additional context or information that might assist reviewers in understanding the changes]

### CODE REVIEW

**Comment by AKSHITHA-CHILUKA** [comment]
#676

**Review by AKSHITHA-CHILUKA — COMMENTED** [review]
added models used and libraries needed and steps for installation

**Review by Akshat111111 — COMMENTED** [review]
everything should be inside your folder

**Comment by AKSHITHA-CHILUKA** [comment]
But readme.md file should be visible in the repo right

**Review by AKSHITHA-CHILUKA — COMMENTED** [review]
added into the folder

**Pull request closed without merging**
