### PR TITLE
Added workflow for successful PR merge

### LINKED ISSUE #101: Adding a thanking workflow
After success of the PR there should be a message of Thankyou for contributing to this repository.

### PR DESCRIPTION
**Pull request by A-b-i-r-a-m-i-G-S**
Fixes #101 
Uses github workflows to autocomment a thank you message after PR is successfully merged. Please note that the repository settings have to allow external contributors to modify workflows, or else the functionality will not work.

### CODE REVIEW

**Review by Akshat111111 — APPROVED** [review]
Good work.

**Comment by Akshat111111** [comment]
> Welcome to Our repository.🎊 Thank you so much for taking the time to point this out.

How its coming before the PR merged ??

**Comment by A-b-i-r-a-m-i-G-S** [comment]
This message is due to #79 . It’s not part of my workflow.

**Comment by Akshat111111** [comment]
yeah now I got it.

**Comment by A-b-i-r-a-m-i-G-S** [comment]
@Akshat111111 please add the labels gssoc and level2 for the PR. Thanks

**Pull request merged**
