### PR TITLE
Added restaurant revenue prediction using machine learning

### LINKED ISSUE #550: 💡[FEATURE]:  Restaurant Revenue prediction using Machine learning
**Is your feature request related to a problem? Please describe.**
yes, it is related to the financial sector for predicting the revenue and making analysis of factors that affect the revenue of the restaurant.

**Describe the solution you'd like**
i will predict the Restaurant revenue from the various input fields like cuisine , location , rating, seating capacity meal price range, marketing or advertisement done or not , social media followers , avg customer visited  using machine learning techniques and display output using a Streamlit based web application with proper analysis ,prediction EDA , feature engineering. i will try multiple ml models as well.

dataset link : https://www.kaggle.com/datasets/anthonytherrien/restaurant-revenue-prediction-dataset

### PR DESCRIPTION
**Pull request by RajKhanke**
- Closes #550 

## 📝 Description
This project focuses on predicting restaurant revenue using a machine learning model, specifically a pre-trained Random Forest model. Users provide input features including location, cuisine type, rating, seating capacity, social media followers, chef experience in years, number of reviews, average review length, ambience score, service quality score, parking availability, weekend and weekday reservations, marketing budget in rupees, and average meal price in rupees. These inputs are preprocessed and transformed, with categorical variables encoded and log transformations applied where necessary. The app, built with Streamlit, features a user-friendly interface with custom styling, allowing users to easily input data and receive a revenue prediction. The model's predictions are based on these detailed inputs, providing an estimated revenue figure that can help restaurant owners make informed business decisions. The project demonstrates effective data preprocessing, feature engineering, and model deployment in a visually appealing web application.

algorithm used : Linear regression , random forest , decision trees , XGBoost

## 🔍 Type of PR

- [ ] 🐛 Bug fix
- [X] ✨ Feature enhancement
- [ ] 📚 Documentation update
- [ ] 🛑 Other (specify): _______________

## 📸 Screenshots / 🎥 Videos (if applicable)

https://github.com/user-attachments/assets/07b43c18-ce24-400c-a14f-539c7d13a815

## ✅ Checklist

- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

I Have also added the stock analysis and prediction using LSTM of hotel chain company Indian hotels  company private limited (INDHOTEL.NS)

### CODE REVIEW

**Comment by RajKhanke** [comment]
@Akshat111111 please merge this PR along with goosc'24 label and appropriate level

**Review by Akshat111111 — COMMENTED** [review]
there is a web app folder so put your folder inside it.Apart from it put the existing files that are present there by making Loan web app folder inside that webapp folder

**Comment by RajKhanke** [comment]
@Akshat111111 all required changes are dome now, please merge this pr along with appropriate level and label of gssoc'24

**Comment by RajKhanke** [comment]
@Akshat111111 please take a look towards this work

**Comment by RajKhanke** [comment]
@Akshat111111  ?

**Review by Akshat111111 — COMMENTED** [review]
fine

**Pull request merged**
