### PR TITLE
Comprehensive Model Evaluation section added to credit risks Model

### PR DESCRIPTION
**Pull request by FreeSpirit11**
Implemented a "Comprehensive Model Evaluation" section with advanced metrics and visualizations for a deeper understanding of model performance.

In "Hedging-of-Financial-Derivatives/Credit Risk /CreditRisk.ipynb"  Used a variety of metrics like ROC-AUC, Precision-Recall, F1-score, and Confusion Matrix in addition to accuracy to get a more comprehensive understanding of model performance.

### CODE REVIEW

**Comment by FreeSpirit11** [comment]
Resolves #171

**Review by Akshat111111 — COMMENTED** [review]
there are conflict so kindly remove it

**Comment by FreeSpirit11** [comment]
Hi @Akshat111111 , I have resolved all the merge conflicts in this PR. Now you can check it again and please tell me if anymore changes needed.

**Comment by Akshat111111** [comment]
I will suggest to create a new PR, so that it will not have unnecessary commits.

**Comment by FreeSpirit11** [comment]
Sure, I will create a new PR.

**Pull request closed without merging**
