### PR TITLE
Credit Score Classifcation using Machine Learning 

### LINKED ISSUE #411: 💡[FEATURE]: Credit score classification using Machine Learning
**Is your feature request related to a problem? Please describe.**

This project aims to classify the credit score of the personality as high, medium, low based on various input features like age, occupation, income, homeownership, assets, dependents, liabilities etc.

It will help to identify the pattern and trends which affects the credit score of a customer

**Describe the solution you'd like**
I will train the machine learning model on given Kaggle dataset :
https://www.kaggle.com/datasets/eneskosar19/credit-score-classification-clean-data

i will also do a complete data analysis and EDA, comparison between various algorithms and write my all setup and work under readme.md

**Describe alternatives you've considered**
on an alternative i can also predict the credit score (regression  method) if found relevant data.

**Additional context**
none

### PR DESCRIPTION
**Pull request by RajKhanke**
## 🛠️ Related Issue

- Closes #411 

## 📝 Description
This project classifies the credit score of the user as high (good) , low (poor) or medium range (standard) based on various input features like age , occupation , annual income , number of bank accounts and credit cards , type of credits , payment behavior , previous payment history etc. The project is hosted using a streamlit application. the model is trained on kaggle data consisting of nearly 1 lakh+ rows. Four machine learning models KNN , GBM , XGBOOST and Random Forest were applied and KNN got the highest 87 % accuracy after stratified k-fold cross validation. also the web application provided info regarding credit score, it stats , significance , graphs and news for new users using NewsAPI Api key.

I have also created readme.md file for reference and setup and entire data preprocessing to model training and deployment information is in ipynb file.

model statistics :
KNN : 87 % accuracy 
XG-Boost : 79 % accuracy
GBM : 74 % accuracy
Random Forest : 72 % accuracy

## 🔍 Type of PR

- [X] ✨ Feature enhancement

## 📸 Screenshots / 🎥 Videos (if applicable)

https://github.com/Akshat111111/Hedging-of-Financial-Derivatives/assets/137288727/0dade9fe-6868-4cdf-a9e8-79c7b2a7d8b1

## ✅ Checklist

- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by RajKhanke** [comment]
please merge this PR along with label and level (3) as a Gssoc'24 part.

**Review by Akshat111111 — COMMENTED** [review]
kindly put your folder  inside financial domain folder

**Comment by RajKhanke** [comment]
@Akshat111111  now i have moved the folder to financial domain, please check changes and merge with level and label

**Review by Aditya-dom — APPROVED** [review]
LGTM!

**Review by Akshat111111 — COMMENTED** [review]
yeah, now its fine

**Pull request merged**
