### PR TITLE
Enhance Cointegration Strategy with Johansen Test

### PR DESCRIPTION
**Pull request by bhanushri12**
## 🛠️ Related Issue  #302

- Closes #[302]

#### Initial Setup

Initially, the project utilized the Engle-Granger (EG) cointegration test to identify pairs of stocks for a trading strategy. The steps involved in this process were as follows:

1. **Engle-Granger Cointegration Test**:
   - Pairwise testing for cointegration between different stock pairs.
   - The test produced a p-value indicating the likelihood of cointegration.
   - Pairs with p-values below a certain threshold (e.g., 0.05 for 95% confidence) were considered cointegrated.
   - A specific stock pair identified via this method was used for backtesting.

#### Implementing Changes

To improve the strategy, the Johansen cointegration test was introduced, which considers a system of equations and can identify multiple cointegration vectors. Here’s what was done:

1. **Implement Johansen Cointegration Test**:
   - The Johansen test was applied to stock pairs, replacing the EG test.
   - The Johansen test evaluates multiple cointegration relationships simultaneously, providing test statistics and critical values for determining cointegration.
   - The stock pair with the highest test statistic (indicating the strongest cointegration) was selected for the trading strategy.

2. **Backtesting with Johansen Pair**:
   - The trading strategy was backtested using the stock pair identified by the Johansen test.
   - The performance metrics, including CAGR, were calculated and compared to the previous results obtained using the EG test.

### Explanation of the Results

1. **Higher CAGR with Johansen Test**:
   - The backtesting results showed that the trading strategy using the stock pair identified by the Johansen test had a higher CAGR compared to the pair identified by the EG test.
   - Specifically, the Johansen-selected pair yielded a CAGR of 36.888%, whereas the EG-selected pair yielded a CAGR of 32.549%.

2. **Why the Result is Better**:
   - **Robustness of Johansen Test**: The Johansen test is considered more robust because it can handle multiple cointegration relationships and provides a system-wide perspective. This makes it more effective in identifying stronger cointegration pairs compared to the pairwise EG test.
   - **Higher Test Statistic**: The stock pair selected by the Johansen test had a higher test statistic, indicating a stronger and more reliable cointegration relationship. This leads to better performance in the trading strategy.
   - **System-Wide Approach**: By considering the entire system of stock prices, the Johansen test can identify relationships that might be overlooked by the EG test, which focuses on pairs independently.

### Summary of Changes Made

1. **Replaced EG Test with Johansen Test**:
   - Applied Johansen test for identifying cointegrated pairs.
   - Selected the pair with the highest test statistic from the Johansen test.

2. **Backtested New Pair**:
   - Conducted backtesting with the new pair identified by the Johansen test.
   - Compared performance metrics (CAGR, Sharpe ratio, etc.) with those from the EG test.

### Code Snippet for Changes

Here’s a summary of the code changes made to implement the Johansen test:

#### Original Code with EG Test

```python
def cointegration_test(stock_data, stocks):
    N = stock_data.shape[1]
    pvalues = np.ones((N, N))
    stock_pairs = []

    for i in range(N):
        for j in range(N):
            if i == j:
                continue

            result = coint(stock_data[stocks[i]], stock_data[stocks[j]])
            pval = result[1]
            pvalues[i][j] = pval

            if pval < 0.05:
                stock_pairs.append((pval, (stocks[i], stocks[j])))

    return pvalues, stock_pairs

pvalues, stock_pairs = cointegration_test(stock_data, stocks)
```

#### Updated Code with Johansen Test

```python
import statsmodels.tsa.vector_ar.vecm as vecm

def johansen_cointegration_test(stock_data, stocks):
    N = stock_data.shape[1]
    test_stats = np.zeros((N, N))
    stock_pairs = []

    for i in range(N):
        for j in range(N):
            if i == j:
                continue

            data = stock_data[[stocks[i], stocks[j]]]
            result = vecm.coint_johansen(data, det_order=0, k_ar_diff=1)
            test_stat = result.lr1[0]  # Using the trace statistic
            critical_value = result.cvt[0, 1]  # Critical value at 95%

            test_stats[i][j] = test_stat

            if test_stat > critical_value:
                stock_pairs.append((test_stat, (stocks[i], stocks[j])))

    return test_stats, stock_pairs

test_stats, johansen_stock_pairs = johansen_cointegration_test(stock_data, stocks)
```

### Conclusion

The transition from using the Engle-Granger test to the Johansen test resulted in identifying a pair with a stronger cointegration relationship, leading to a higher CAGR in the backtest. This demonstrates the Johansen test's effectiveness in enhancing the performance of the cointegration-based trading strategy.

## 🔍 Type of PR
- [X] ✨ Feature enhancement

## ✅ Checklist

- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by Akshat111111 — COMMENTED** [review]
good work!, Kindly put this file inside Nifty folder

**Comment by bhanushri12** [comment]
@Akshat111111 should I create a separate directory in the Nifty Folder and upload?

**Review by Akshat111111 — COMMENTED** [review]
yeah, it works

**Comment by Akshat111111** [comment]
kindly add your file in the main nifty

**Pull request merged**
