### PR TITLE
here is my Car price  finacial prediction and analysis

### PR DESCRIPTION
**Pull request by PRIYANSHU2026**
i have didnt put in any folder because i dindent got relevent folder

### CODE REVIEW

**Review by Akshat111111 — COMMENTED** [review]
in the same notebook, add the analysis of some cars stock and put the entire folder inside nifty

**Comment by PRIYANSHU2026** [comment]
Done sir

**Review by Akshat111111 — COMMENTED** [review]
resolve the conflict

**Comment by PRIYANSHU2026** [comment]
done

**Review by Akshat111111 — COMMENTED** [review]
now also same

**Pull request closed without merging**
