### PR TITLE
Added more visualisations to Crude oil forecasting Model

### PR DESCRIPTION
**Pull request by FreeSpirit11**
To enhance the model and provide more visualizations, I added the following:

**1.Feature Importance Visualization:** visualized the feature importance scores obtained from the model, which can provide insights into which features contribute the most to predicting crude oil prices.

**2.Actual vs Predicted Plot Over Time:** Plotted the actual and predicted crude oil prices over time to provide a visual representation of how well the model performs across different time periods.

**3.Residual Analysis:** Plotted the residuals (the differences between actual and predicted values).

### CODE REVIEW

**Comment by FreeSpirit11** [comment]
Resolves #121

**Review by Akshat111111 — APPROVED** [review]
Nice work.

**Comment by amishhaa** [comment]
@Akshat111111 According to this PR's Plot of 'Impact of feature ablation on model MSE' , the most important feature should be USdollar BTC and Gold but the contributor has written "From the following plot we can conclude that USdollar is the most important feature for forcasting CrudeOil price followed by BTC(Bitcoin) and Naturalgas." which was reflective of the previous work's conclusions hence keeping it the same is wrong and contrary to what we have deduced from our new plots. 
Additionally there is another new Plot of 'Feature Importance' under 'Additional Visualization' which again contradicts entire findings and conclusions of 'Analysis of Results' Topic and the contradictions were never explained(see 'Impact of feature abalation plot') which plots importance of feature. 'Actual vs Predicted Crude Oil Prices' is plotted twice and the intention is unclear as to why it has been plotted twice in this PR. Findings from 'Residual Plot' is never explained and is unclear why it was plotted in the first place if there were no conclusions from it. I would appreciate if you look into these errors as they caught my eye, thank you.

**Comment by FreeSpirit11** [comment]
Hi @amishhaa ,

In the new visualizations, I did not include the statement 'From the following plot we can conclude that USdollar is the most important feature for forecasting CrudeOil price followed by BTC(Bitcoin) and Naturalgas.' This statement was part of the previous visualization, which accurately reflected the findings from that analysis. The new visualization is intended to provide additional insights and may be helpful for future reference.

I included the plot of 'Actual vs Predicted Plot Over Time' twice because the initial plot lacked grid lines and did not appear as visually appealing.

Also when you are mentioning that for Residual Analysis I have not explained the plot , I must say that I'm generating additional visualizations to enrich understanding and enable future explorations, rather than offering interpretations for each plot's significance.

**Comment by amishhaa** [comment]
If you change the Plots of an existing work you also have to account for the deductions that were made using that Plot.
The initial Plot was
debate1
here clearly Usdollar BTC and natural gas have the highest impact.
you changed the plot to
debate2
now the statement 'From the following plot we can conclude that USdollar is the most important feature for forecasting CrudeOil price followed by BTC(Bitcoin) and Naturalgas.' doesn't hold. Changing the Plots but not the deductions can cause such discrepancies.

Secondly, your Plot for 'Feature Importance' (see In[16]) assumes linear relationships amongst features and target which is clearly Wrong as the features and target have non linear relationship. The work in //Analysis of the results// has excluded one feature at a time and plotted the Error caused due to absence of that feature this is one of the method used to determine importance of feature in complex non linear relationships. Therefore the plot 'Feature Importance' is incorrect in the current context.

Thank you for enhancing  'Actual vs Predicted Plot Over Time' but you could have done it in-place if the initial plot wasn't visually appealing and it belongs to the //Testing// subtopic.


Adding 2 lines on why residual analysis was used and what it signifies doesn't hurt. It enriches understanding and enables future explorations :)
I am quite inexperienced and the goal of these posts was to make sure @Akshat111111 acknowledges these discrepancies.

**Comment by FreeSpirit11** [comment]
Actually your first point is correct. So for that I will create a new pull request and make the changes. Or if you want to edit it, you can create a pull request. Thanks for the help @amishhaa :)

**Comment by FreeSpirit11** [comment]
Hi  @Akshat111111 , Please assign labels **GSSOC**  and **level 2** to this PR else it wont update in Leader board as mentioned in latest GSSOC guidelines.

**Pull request merged**
