### PR TITLE
Flight Fare Prediction App #276

### PR DESCRIPTION
**Pull request by Pranshu-jais**
## 🛠️ Related Issue

- Closes #[issue_number]

## 📝 Description

[Python Flight Fare Prediction App, that returns the fare prediction for a given set of travel details, like:  departure date, arrival date, departure city, arrival city, stoppages, and the airline carrier.]

## 🔍 Type of PR

- [ ] 🐛 Bug fix
- [x] ✨ Feature enhancement
- [ ] 📚 Documentation update
- [ ] 🛑 Other (specify): _______________

## 📸 Screenshots / 🎥 Videos (if applicable)

[Attach screenshots or videos]

## ✅ Checklist

- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## ℹ️ Additional Context

[Include any additional context or information that might assist reviewers in understanding the changes]

### CODE REVIEW

**Review by Akshat111111 — COMMENTED** [review]
There is a web app folder so put your folder there

**Comment by Pranshu-jais** [comment]
Sir , do you mean this folder Hedging-of-Financial-Derivatives
/Webapp

**Comment by Pranshu-jais** [comment]
I  maked a new folder as Python Web apps and put my flight_fare_prediction_web_app folder over there.

**Review by Akshat111111 — COMMENTED** [review]
yeah, it works

**Pull request merged**
