### PR TITLE
Mastercard Stock Price Prediction using LSTM, SVM And K-Nearest Neighbors (KNN)

### LINKED ISSUE #437: [FEATURE]: Mastercard Stock Price Prediction using LSTM, SVM And K-Nearest Neighbors (KNN)
**Is your feature request related to a problem? Please describe.**
Yes, The art of forecasting stock prices has been a difficult task for many of the researchers and analysts. Investors eagerly seek effective stock price prediction systems to guide successful investments and understand future market trends.

**Describe the solution you'd like**
I would like to Add the ML Models which i am gonna build like using LSTM, SVM and  K-Nearest Neighbors (KNN)  using historical stock price data and relevant financial indicators, preprocess the data, performing EDA, and check the prices, and compare the model's accuracy.

Describe alternatives you've considered
Exploring additional models like ARIMA, XGBoost, or ensemble methods for potential improvement in forecasting accuracy.

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
## 🛠️ Related Issue
Fixes #437 

## 📝 Description

Predicting Mastercard Stock Prices involves using various machine learning models like LSTM (Long Short-Term Memory), SVM and k - nearest neighbours  to analyze historical stock data and forecast future trends. Each model leverages different algorithms and methodologies to enhance prediction accuracy and reliability.

## 🔍 Type of PR

- [x] ✨ Feature enhancement
- [x] 📚 Documentation update

## ✅ Checklist

- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by aditya-bhaumik** [comment]
@Akshat111111 please assign me the Gssoc labels  and review and merge this pull request

**Review by Akshat111111 — COMMENTED** [review]
its part of nyse, so put your entire folder under it

**Comment by aditya-bhaumik** [comment]
@Akshat111111 i have made the changes requested please review my pull request and merge it

**Comment by aditya-bhaumik** [comment]
@Akshat111111 please merge my pull request

**Review by Akshat111111 — COMMENTED** [review]
in the code, there is writtenn zomato high price, so correct it

**Comment by aditya-bhaumik** [comment]
@Akshat111111 made the changes requested

**Review by Akshat111111 — COMMENTED** [review]
yeah, its fine.But the accuracy can be increased

**Pull request merged**
