### PR TITLE
Implementation for NYSE banking sector stocks

### PR DESCRIPTION
**Pull request by michaelfred533**
Added Jupyter notebook that implements the same code with top NYSE banking sector stocks. The new jupyter notebook is in the new NYSE folder.

### CODE REVIEW

**Comment by Akshat111111** [comment]
Really nice implemented the same for the banks of United States. Thankyou for your time in working on this project.

**Comment by Akshat111111** [comment]
Are you working on the implemetation for the different sectors of NYSE?? 
You have also good knowledge of quantitative finance, which field you find more intresting??

**Comment by michaelfred533** [comment]
Thank you too, I'm happy to help with this project. And yes, I'm trying out the implementation with different sectors of the NYSE, I can add those files in if I find something interesting. I was reading some textbooks and things about finance a couple years ago and I had always been interested in mean reversion and pairs trading. Which field do you find most interesting?

**Comment by Akshat111111** [comment]
Oh that's great, what sector you have chosen now ?? The thing I find most intresting is about Algorithmic trading and Scalping trading.I am also working on the implementation it in this Pairs Trade code making it more efficient.

**Comment by michaelfred533** [comment]
I was looking at Technology sector but I'll try a couple different sectors too. The banking sector looked better than technology. I'm interested in scalp trading as well.

**Comment by Akshat111111** [comment]
Oh thats great, I'm currently working on the scalping project that I will add in the github soon.Will definately work on it.

**Pull request merged**
