### PR TITLE
Arima

### PR DESCRIPTION
**Pull request by misskiran**
I was given the ARIMA  implementation and I have taken a historical Dataset from official website of NIFTY 50 . I have made sure that the data is stationary before feeding to the model,  Tested on dickey fuller. Defined the model parameters p,d,q ,using AIC and BIC .Trained and made predictions .

### CODE REVIEW

**Comment by Akshat111111** [comment]
Make a separate folder of it so that it will be more organized

**Review by Akshat111111 — COMMENTED** [review]
NSE should be the main folder then ARIMA will be sub folder which carry the dataset and implementation.

**Comment by misskiran** [comment]
Okayy

**Comment by misskiran** [comment]
Done....

**Review by Akshat111111 — COMMENTED** [review]
Dont put the arima into NYSE, I have already said that make NSE as the folder and inside it make ARIMA implementation another folder

**Comment by misskiran** [comment]
My Bad..Please Check now.

**Review by Akshat111111 — APPROVED** [review]
Now its fine.

**Pull request merged**
