### PR TITLE
Smart Financial Advisory added

### PR DESCRIPTION
**Pull request by ashis2004**
#640 resolved

### CODE REVIEW

**Comment by ashis2004** [comment]
@Akshat111111 pls check it

**Review by Akshat111111 — APPROVED** [review]
fine

**Comment by sanjay-kv** [comment]
Hey we missed this repo to add in contribution limit, just noticed this is simillar to folder structure, as you have already contributed only 250 points will be allocated and dont contribute more. @ashis2004

**Comment by ashis2004** [comment]
pls sir don't deduct points after that i'll not make PR @sanjay-kv

**Comment by sanjay-kv** [comment]
I will go through it and let you know

**Comment by ashis2004** [comment]
My precious time has invested ...my classes are going on. pls sir @sanjay-kv

**Pull request merged**
