### PR TITLE
Here is my model of finance of Udemy EDA visualization

### PR DESCRIPTION
**Pull request by PRIYANSHU2026**
About Dataset.           issue no #213 
Context
A compilation of all the development related courses ( 13 thousand courses) which are available on Udemy's website. Under the development category, there are courses from Finance, Accounting, Book Keeping, Compliance, Cryptocurrence, Blockchain, Economics, Investing & Trading, Taxes and much more each having multiple courses under it's domain.
All the details can be found on [Udemy's website](https://www.udemy.com/?utm_source=adwords-brand&utm_medium=udemyads&utm_campaign=Brand-Udemy_la.EN_cc.INDIA&utm_term=_._ag_78279294239_._ad_450776424635_._de_c_._dm__._pl__._ti_kwd-310556426868_._li_1007785_._pd__._&utm_term=_._pd__._kw_udemy_._&matchtype=e&gclid=EAIaIQobChMIgaPGkarj6wIViSQrCh1weAXPEAAYASAAEgIhuvD_BwE) as well!

Content
Here, I have extracted data related to 10k courses which come under the development category on Udemy's website.
The 17 columns in the dataset can be used to gain insights related to:

id : The course ID of that particular course.
title : Shows the unique names of the courses available under the development category on Udemy.
url: Gives the URL of the course.
is_paid : Returns a boolean value displaying true if the course is paid and false if otherwise.
num_subscribers : Shows the number of people who have subscribed that course.
avg_rating : Shows the average rating of the course.
avg rating recent : Reflects the recent changes in the average rating.
num_reviews : Gives us an idea related to the number of ratings that a course has received.
num_ published_lectures : Shows the number of lectures the course offers.
num_ published_ practice_tests : Gives an idea of the number of practice tests that a course offers.
created : The time of creation of the course.
published_time : Time of publishing the course.
discounted_ price_amount : The discounted price which a certain course is being offered at.
discounted_ price_currency : The currency corresponding to the discounted price which a certain course is being offered at.
price_ detail_amount : The original price of a particular course.
price_ detail_currency : The currency corresponding to the price detail amount for a course.

### CODE REVIEW

**Comment by Amarta113** [comment]
@PRIYANSHU2026 I was working on the same dataset that you used.

**Comment by Akshat111111** [comment]
> @PRIYANSHU2026 I was working on the same dataset that you used.

@Amarta113 you can do a different thing with this dataset

**Review by Akshat111111 — COMMENTED** [review]
I have already merged a pr for the same.Dont make different PR for the same work

**Comment by PRIYANSHU2026** [comment]
Yes sir

**Pull request closed without merging**
