### PR TITLE
Added eth price prediction

### PR DESCRIPTION
**Pull request by Aditijainnn**
## 🛠️ Related Issue

- Closes #[issue_number]
- #567

## 🔍 Type of PR

- [ ] 🐛 Bug fix
- [x] ✨ Feature enhancement
- [ ] 📚 Documentation update
- [ ] 🛑 Other (specify): _______________

## 📸 Screenshots / 🎥 Videos (if applicable)

[Attach screenshots or videos]

## ✅ Checklist

- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by Akshat111111 — COMMENTED** [review]
put inside that decentralized finance folder

**Comment by Aditijainnn** [comment]
what's that?

**Comment by Akshat111111** [comment]
> what's that?

its pre existing folder

**Comment by Aditijainnn** [comment]
> > what's that?
> 
> its pre existing folder

okay

**Pull request closed without merging**
