### PR TITLE
Enhanced Feature Engineering for Crisis Prediction

### PR DESCRIPTION
**Pull request by FreeSpirit11**
Enhancing Feature Engineering for Banking Crisis Prediction Model

Description:
The code introduces several feature engineering techniques to improve the predictive performance of the banking crisis prediction model.

Interaction Terms: Multiplication of 'systemic_crisis' and 'domestic_debt_in_default' to capture their interaction effect.
Ratio Features: Calculation of the ratio between 'exch_usd' and 'inflation_annual_cpi' to provide a normalized exchange rate.
Moving Averages: Computation of the 3-month moving average of 'gdp_weighted_default' to smooth out short-term fluctuations.
Difference Features: Calculation of the difference in 'inflation_annual_cpi' between consecutive years to capture changes over time.
Categorical Aggregations: Aggregation of mean inflation rates for each level of the 'banking_crisis' variable to provide additional insights.
These feature engineering techniques aim to extract more meaningful information from the existing data, potentially enhancing the model's ability to predict banking crises in African economies.

### CODE REVIEW

**Comment by FreeSpirit11** [comment]
Hi @Akshat111111 , Please assign labels GSSOC and level 2 to this PR.

Resolves #266 .

**Review by Akshat111111 — COMMENTED** [review]
Kindly change the file name, untitled is there

**Comment by FreeSpirit11** [comment]
Hi @Akshat111111 , I have changed the file name to "African_Crisis_Prediction.ipynb".

**Review by Akshat111111 — COMMENTED** [review]
yeah, now its fine

**Pull request merged**
