### PR TITLE
Stock market Data Scrapper from yahoo Finance

### LINKED ISSUE #386: 💡[FEATURE]: An application which can scrap stock price data of any inputed company in csv format from Yahoo Finance
**Is your feature request related to a problem? Please describe.**
many times we require stock price data of many financial firms (for ex: NVidia) for various purposes and projects (like stock price prediction). This Streamlit based application can give you scrapped data from yahoo finance (in processed form)  which can be downloadable in csv format, often useful for various financial operations

**Describe the solution you'd like**
using web scrapping library beautify soup in python this project scraps stock market data from yahoo finance site of any user defined company that is available on site. 

**Additional context**
none

### PR DESCRIPTION
**Pull request by RajKhanke**
- Closes #386 

## 📝 Description

This project scraps the  data of any inputted company listed under stock exchange of user inputted starting and ending date (both should be valid) and download it in csv format. The project contains another section where about 10,000 companies are listed with their ticker symbol, as user has to enter ticker symbol of company to fetch the data. user can see ticker information by searching in database and then enter the ticker symbol and date to obtain the required data. This data can be used for various purposes , projects and for machine learning model like stock price prediction for various companies.

The yfinance library is used for stock data scrapping and ticker. json data scrapped from internet  is used for ticker information display.

I have attached one reamde.md and one webapp_scrapper.mp4 file for demonstration as well.

## 🔍 Type of PR

-  ✨ Feature enhancement

## 📸 Screenshots / 🎥 Videos (if applicable)

https://github.com/Akshat111111/Hedging-of-Financial-Derivatives/assets/137288727/a5435188-9914-496d-922b-4f13a9abf1cb

## ✅ Checklist

- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by RajKhanke** [comment]
@Akshat111111 please merge this pr along with gssoc'24 label and level (level 2 as assigned). This will resolve **issue no. 386**.

**Review by Akshat111111 — COMMENTED** [review]
kindly put your entire folder inside financial domain

**Comment by RajKhanke** [comment]
@Akshat111111  i have move the project under financial domain directory. please kindly merge this PR along with Gssoc level and label.

**Review by Akshat111111 — COMMENTED** [review]
yeah, now its fine

**Pull request merged**
