### PR TITLE
Added Diamond price prediction using Machine learning

### LINKED ISSUE #481: 💡[FEATURE]: Diamond Price prediction using Machine learning
**Is your feature request related to a problem? Please describe.**

Assets are important aspects of financial derivatives and one of them are diamonds. This project aims to predict the estimated price of diamonds in market using machine learning and regression techniques by taking different inputs from user -:
1)diamond weight in carats
2) diamond's shape in x, y and z axis
3)diamond's color and cutting quality
4)depth
5)width of widest point and sharpness etc.

**Describe the solution you'd like**
i will train machine learning models on following data :
https://www.kaggle.com/datasets/amirhosseinmirzaie/diamonds-price-dataset
i will do complete data Science procedures including analysis ,EDA , feature engineering and processing and deployed the trained model with the help of application (GUI) using Streamlit package in python.

**Additional context**
None

### PR DESCRIPTION
**Pull request by RajKhanke**
## 🛠️ Related Issue

- Closes #481 

## 📝 Description
This Streamlit application predicts diamond prices based on user-input diamond characteristics and provides dynamic information about diamonds fetched from a website. It incorporates a machine learning model trained to predict diamond prices using features like carat weight, cut, color, clarity, and dimensions. Users can interactively input these attributes through a user-friendly interface and receive predicted price estimates instantly.

The application includes three main functionalities accessed through a sidebar navigation:

Diamond Price Prediction: Users input diamond characteristics such as carat weight, cut type, color, clarity, depth, table, and dimensions. Upon clicking the "Predict Price" button, the app utilizes a pre-trained machine learning model to compute and display the predicted diamond price in lakhs.

Dataset View: This section allows users to explore a dataset (diamonds.csv in this example) containing historical diamond data. The dataset is displayed in a tabular format using Streamlit's st.dataframe function, providing insights into various attributes and prices of diamonds.

models used :
decision tree (97 %)
random forest (98 %)
linear regression (90 %)
support vector machine (87 %)

I have also done eda, feature engineering and created a complete reference and setup file readme.md
## 🔍 Type of PR

- [ ] 🐛 Bug fix
- [X] ✨ Feature enhancement
- [ ] 📚 Documentation update
- [ ] 🛑 Other (specify): _______________

## 📸 Screenshots / 🎥 Videos (if applicable)

https://github.com/user-attachments/assets/1b82eead-1926-4673-842b-9f06e2036478

## ✅ Checklist

- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by RajKhanke** [comment]
@Akshat111111 please merge this pr along with level (3) and label of gssoc'24. this will resolve issue number 481

**Comment by RajKhanke** [comment]
@Akshat111111 please look towards this PR

**Comment by RajKhanke** [comment]
@Akshat111111 please look forwards towards this PR

**Review by Akshat111111 — COMMENTED** [review]
Good work

**Pull request merged**
