### PR TITLE
Nvidia Stock Prediction

### LINKED ISSUE #369: 💡[FEATURE]: Add Nvidia Stock Prediction using LSTM
**Is your feature request related to a problem? Please describe.**

I'd like to propose a new feature for the project that enables Nvidia stock price prediction using LSTM. This feature would allow users to leverage Lwt's concurrency capabilities to fetch historical stock data, train a machine learning model for prediction.

### PR DESCRIPTION
**Pull request by Nidhi1314**
## 🛠️ Related Issue

- Closes #369 

## 📝 Description

This pull request adds a new nvidia_stock_prediction folder containing functionality to predict stock prices for Nvidia (NVDA).

### The nvidia_stock_prediction folder includes:
* nvidia_stock_prediction.py: The core Python script for building, training, and evaluating the LSTM model.
* The script also contains a CSV file containing historical daily data on Nvidia stock prices. 
* Readme file : for a comprehensive understanding of this new feature proposed.

## 🔍 Type of PR

- [ ] 🐛 Bug fix
- [x] ✨ Feature enhancement
- [ ] 📚 Documentation update
- [ ] 🛑 Other (specify): _______________

## 📸 Screenshots / 🎥 Videos (if applicable)

image

## ✅ Checklist

- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Nidhi1314** [comment]
@Akshat111111 please review it. If there is something to correct let me know.

**Review by Akshat111111 — COMMENTED** [review]
everything is fine.  Kindly put your entire folder inside NYSE

**Comment by Nidhi1314** [comment]
@Akshat111111 I have moved the folder to NYSE, now you may merge.

**Review by Akshat111111 — COMMENTED** [review]
yeah, it works

**Pull request merged**
