### PR TITLE
Updated the PULL REQUEST readme template URGENT:🚨

### LINKED ISSUE #48: Real Estate Price Prediction Model
I would like to build a Real Estate Price Prediction Model, if this enhancement aligns with the goal of this project can i go ahead and start working on this ?

### LINKED ISSUE #61: OCR implementation of financial documents
The Optical character recognition or optical character reader (OCR) is the conversion of images of typed, handwritten or printed text into machine-encoded text, from a scanned documents

### LINKED ISSUE #62: Decentralized Finance (DeFi) Integration
You can implement using any of the existing technologies

### LINKED ISSUE #63: 2024 Indian election sentimental analysis
The task is to find the sentiments and corelation with financial market movement.

### LINKED ISSUE #140: Foreign Exchange (Forex) Rate Prediction
I am interested to create a model to forecast currency exchange rates between different countries based on factors like interest rates, inflation, trade balances, political stability. 
I request to be assigned this with appropriate GSSOC tags

### LINKED ISSUE #183: Loan Status Prediction Model
**Is your feature request related to a problem? Please describe.**
Explore a dataset with parameters like the date of loan taken, credits etc.  and Predict whether the loan would be approved or not.

**Describe the solution you'd like**
I would like to use support vector Machine to make this predictive system.

**Describe alternatives you've considered**
It can further be transformed to a deep learning model which can fetch the fluctuations and accordingly draw conclusions.

**Additional context**

### LINKED ISSUE #185: 💡[FEATURE]: Stock Price prediction using FB Prophet
✔️Developed a Facebook Prophet machine learning model to forecast Tesla stock prices 30 days ahead, utilizing data sourced from Yahoo Finance. 
✔️Employed Google Finance, extracted financial data into Google Sheets for preprocessing. 
✔️The model's predictions were compared with actual data, and its performance was rigorously evaluated, providing insights into its effectiveness in predicting future stock prices.

### LINKED ISSUE #210: 💡[FEATURE]: Create additional visualizations for Indian Elections Model.
For a deeper understanding of SENSEX performance around Indian general elections I will create following additional visualisations:

1. **Correlation Heatmap**
2. **Volatility Comparison Plot**
3. **Cumulative Returns Plot**
4. **Density Plot of Returns**

### LINKED ISSUE #230: 🪲[Bug]:  Close issues that got PR merged but not linked properly
Please assign the issue to me
Hey @Akshat111111 , Bro i have made the necessary changes and generated a PR , please assign this issue and the PR with an appropriate GSSoC'24 tag.

### PR DESCRIPTION
**Pull request by binguliki**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
`Here is the issue where most people go wrong that they fail to link the issue properly before merging the PR`

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [x] Bug fix

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Because of the poor structuring of the PR template it has been disturbing the workflow of the entire PROJECT , I have updated the  Template FILE to be more readable and understandable for all the contributors.

also i have manually examined all the PR's that had been made earlier but were not linked to the issues properly
by this PR i'll be success fully closing them all.
Here are the issues:
- Closes #63
- Closes #62
- Closes #61
- Closes #48
- Closes #140
- Closes #183
- Closes #185
- Closes #210
- Closes #230 [My Issue]

### CODE REVIEW

**Comment by binguliki** [comment]
@Akshat111111 , Please Provide appropriate Level tag and also the GSSoC'24 contribution tag

**Comment by binguliki** [comment]
@Akshat111111  Hey bro👋 , Can you provide a level-2 tag for this bug if possible

**Comment by Akshat111111** [comment]
> @Akshat111111 Hey bro👋 , Can you provide a level-2 tag for this bug if possible

There was a guideline from gssoc community that documentation and workflow should have level 1

**Review by Akshat111111 — APPROVED** [review]
yeah, it works

**Pull request merged**
