### PR TITLE
Solved #572- Analyzing the Impact of Economic Indicators on Stock Prices

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
## 🛠️ Related Issue

- Closes #[issue_number]
#572
## 📝 Description

[Provide a concise description of the changes. Include the purpose and any relevant context or details.]

## 🔍 Type of PR

- [ ] 🐛 Bug fix
- [x] ✨ Feature enhancement
- [ ] 📚 Documentation update
- [ ] 🛑 Other (specify): _______________

## 📸 Screenshots / 🎥 Videos (if applicable)

[Attach screenshots or videos]

## ✅ Checklist

- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## ℹ️ Additional Context

[Include any additional context or information that might assist reviewers in understanding the changes]

### CODE REVIEW

**Comment by Aditi22Bansal** [comment]
@Akshat111111 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@Akshat111111 
Kindly review and merge this PR

**Comment by Aditi22Bansal** [comment]
@Akshat111111 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@Akshat111111 
Kindly review the PR
and if any changes are required kindly inform
I'll definitely look into it

**Comment by Amarta113** [comment]
> @Akshat111111 Kindly review the PR and if any changes are required kindly inform I'll definitely look into it

@Aditi22Bansal Due to the current workload, he is unable to review all the PRs simultaneously. In the meantime, I think you might want to work on another issue.

**Comment by Aditi22Bansal** [comment]
@Amarta113 
I understand 
Since I am a beginner, I only have some repos which matches my skills, that's why
No problem 
If possible kindly see to this PR before 31st as the gssoc is closing that day and I have worked hard for this so just want to be labelled to get points
Thankyou so much

**Comment by Amarta113** [comment]
@Aditi22Bansal I forgot the due date for the end of GSSoC. Apologies from me too

**Comment by Aditi22Bansal** [comment]
> @Aditi22Bansal I forgot the due date for the end of GSSoC. Apologies from me too

No problem
Just see to it that it gets merged
Thankyou

**Comment by Aditi22Bansal** [comment]
@Akshat111111 
If possible please review and merge this
Only 2 days are remaining after that no pr will be considered

**Comment by Aditi22Bansal** [comment]
@Akshat111111 
Please merge this PR
Tomorrow gssoc is closing

**Comment by Akshat111111** [comment]
> > @Akshat111111 Kindly review the PR and if any changes are required kindly inform I'll definitely look into it
> 
> @Aditi22Bansal Due to the current workload, he is unable to review all the PRs simultaneously. In the meantime, I think you might want to work on another issue.

Thanks for understanding

**Comment by Akshat111111** [comment]
I will review all PRs within the deadline

**Pull request merged**
