### PR TITLE
it is the all group of Adani stock prediction with enhacement

### PR DESCRIPTION
**Pull request by PRIYANSHU2026**
It is all about all groups belong to adani

### CODE REVIEW

**Review by Akshat111111 — COMMENTED** [review]
good work, Kindly add the references so I can merge it

**Comment by PRIYANSHU2026** [comment]
https://www.kaggle.com/datasets/yogesh239/nse-stocks-datasets-adani-group-of-companies from here

**Comment by PRIYANSHU2026** [comment]
no sir

**Review by Akshat111111 — COMMENTED** [review]
Kindly add the reference in the notebook so that I will merge it.

**Comment by PRIYANSHU2026** [comment]
Sure sir

**Comment by PRIYANSHU2026** [comment]
Done sir

**Review by Akshat111111 — COMMENTED** [review]
yeah, now its fine

**Pull request merged**
