### PR TITLE
Netflix Stock Prediction Using Regression 

### PR DESCRIPTION
**Pull request by ashis2004**
## 🛠️ Related Issue

- Closes #[issue_number]
- #480 fixed

## 📝 Description

[Provide a concise description of the changes. Include the purpose and any relevant context or details.]

## 🔍 Type of PR

- [ ] 🐛 Bug fix
- [ ] ✨ Feature enhancement
- [ ] 📚 Documentation update
- [ ] 🛑 Other (specify): _______________

## 📸 Screenshots / 🎥 Videos (if applicable)

[Attach screenshots or videos]

## ✅ Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## ℹ️ Additional Context

[Include any additional context or information that might assist reviewers in understanding the changes]

### CODE REVIEW

**Comment by ashis2004** [comment]
@Akshat111111 pls check it issue #480

**Review by Akshat111111 — COMMENTED** [review]
it should be inside NYSE

**Comment by ashis2004** [comment]
I didn't get @Akshat111111

**Comment by ashis2004** [comment]
i've to make separate folder "NYSE" inside that i've to make PR @Akshat111111

**Comment by ashis2004** [comment]
pls review it @Akshat111111

**Review by Akshat111111 — COMMENTED** [review]
it should be inside NYSE.Make a new pr if you are facing any difficulty

**Comment by ashis2004** [comment]
> it should be inside NYSE.Make a new pr if you are facing any difficulty

I'm not getting all files while cloning pls merge it @Akshat111111

**Comment by Akshat111111** [comment]
make a new branch and try with it

**Comment by ashis2004** [comment]
> make a new branch and try with it

Okay i'll do

**Pull request closed without merging**
