### PR TITLE
Added foreign exchange rate prediction model

### PR DESCRIPTION
**Pull request by anushka7220**
this is the model of foreign exchange rate prediction and it is made using tensorflow and python
Developed an LSTM-based exchange rate prediction model using Python and TensorFlow/Keras. This model forecasts foreign exchange rates based on historical data, aiding in financial decision-making and risk management.
Integrated with the Exchange rate API to fetch reliable and extensive historical exchange rate data for training the model.
Implemented data preprocessing techniques including scaling and sequence generation to prepare input data for the LSTM model.
Trained and optimized the model using TensorFlow and Keras, achieving accurate predictions of exchange rates.Evaluated model performance using standard regression metrics such as Mean Absolute Error (MAE) and Root Mean Squared Error (RMSE).

- [x] Feature enhancement

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by Akshat111111 — COMMENTED** [review]
Nice work, It will be better you also upload a notebook file too with it.Add these two items by creating a new folder named- Forex.

**Comment by anushka7220** [comment]
@Akshat111111 sure!

**Comment by anushka7220** [comment]
@Akshat111111 done!!

**Review by Akshat111111 — APPROVED** [review]
yeah now the work is perfect.

**Comment by anushka7220** [comment]
@Akshat111111 Thanks!

**Pull request merged**
