### PR TITLE
Var

### PR DESCRIPTION
**Pull request by tejasvinigoel**

### CODE REVIEW

**Review by apooyadv — COMMENTED** [review]
It would be good if you add some info about VaR in the notebook itself.

**Review by Akshat111111 — COMMENTED** [review]
yeah, @apooyadv is correct.Also plot the things for better understanding of non technical person.

**Comment by tejasvinigoel** [comment]
kindly check again

**Review by Akshat111111 — APPROVED** [review]
Now its as per the standards

**Comment by tejasvinigoel** [comment]
kindly add gssoc tag

**Pull request merged**
