### PR TITLE
Car Ownership prediction using Machine learning

### LINKED ISSUE #385: Car Ownership prediction using Machine learning
**Is your feature request related to a problem? Please describe.**
yes, car ownership prediction is often related to financial problems. With the machine learning techniques and dataset available on Kaggle we can detect whether the given person owns or capable of owning a car or not thereby helping the financial organization to calculate assets and liabilities.

**Describe the solution you'd like**
By taking different financial inputs from user like their occupation (ex : engineer),monthly income , credit score ,financial status is stable or not, years of employment , number of children we can find out whether the person owns a car or not. we can also correlate which parameters are significantly important related to assets and cars and their correlations.

i will also do a detailed  data analysis and data visualization using Streamlit application

**Additional context**
none

### PR DESCRIPTION
**Pull request by RajKhanke**
- **Closes #385 **

## 📝 Description

This project predicts whether the user has a capability to own a car or not based on many input features like occupation, monthly income, credit score ,year of employment, financial status, financial history , car and number of children.

This project could be useful source in financial field for asset predictability and to measure its association with different input features.

The below csv dataset from Kaggle is used as reference which contains nearly 600+ rows (car_ownership.csv) on which processing is performed to obtained a  processed data processed_data_car.csv , all this processing is performed in first notebook (car_ownership_data_preprocessing.ipynb) file.

https://www.kaggle.com/datasets/rkiattisak/car-ownership-predictionbeginner-intermediate

on this dataset, below processing are performed :
1) feature scaling and column reinitialization
2) errors and outliers removal
3) remove na, missing values , regularization etc.

after Data preprocessing the next step is Exploratory  data analysis using different plotting libraries like matplotlib, pandas, seaborn and plotly. following plots were plotted in this step:-
    1) Pie chart of financial history and financial status types
    2) violin plot of credit scores
    3) box plot of numerical features
    4) count plot of all occupations
    5) heatmap or confusion matrix for four different models of machine learning
    6) model comparison graphs

 The four machine learning model random forest ,decision trees ,logistic regression, gradient boosting machine are selected for model training over the inputted processed data:
     random forest accuracy : 95 %
     GBM accuracy : 96 %
     decision trees accuracy : 93 %
     logistic regression accuracy : 85 %
The 10 fold cross validation is then performed on GBM model to obtained a final average cross validated accuracy of 95 % with 3% of deviation.This Gradient boosting machine model is then loaded into streamlit application after installing and using joblib library.

🔍 Type of PR
 
 ✨ Feature enhancement

✅ Checklist

 I have performed a self-review of my code.
 I have read and followed the Contribution Guidelines.
 I have tested the changes thoroughly before submitting this pull request.
 I have provided relevant issue numbers, screenshots, and videos after making the changes.
 I have commented my code, particularly in hard-to-understand areas.

## 📸 Screenshots / 🎥 Videos (if applicable)

https://github.com/Akshat111111/Hedging-of-Financial-Derivatives/assets/137288727/fe132c08-aed4-4578-aede-3f1c318cce04

### CODE REVIEW

**Comment by RajKhanke** [comment]
@Akshat111111  please merge this along with the gssoc'24 label and level

**Comment by RajKhanke** [comment]
@Akshat111111 this will resolve **issue no . 385** (level2 ,gssoc)

**Review by Akshat111111 — COMMENTED** [review]
kindly put your entire folder inside financial domain

**Review by Akshat111111 — COMMENTED** [review]
also dont forget to add a notebook of any car stock.I will give you level 3 after it

**Comment by RajKhanke** [comment]
@Akshat111111 as you have suggested, i have created a notebook for car company tesla's stock price prediction using LSTM and predicted the next day , next month and next year's stocks.

also i have shifted the entire project to finance domain directory

**Comment by RajKhanke** [comment]
@Akshat111111  for the data for stock price prediction i have used yahoo finance data from 2012-2014 scrapped using my other project feature yahoo finance scrapper , its pull request is also created .please review and merge it as well.

please merge this PR along with Gssoc label and level (2 or 3) whatever you find appropriate.

**Review by Akshat111111 — COMMENTED** [review]
Good work!!

**Pull request merged**
