### PR TITLE
Zomato Stock Price Prediction using LSTM, SVM, SGD, Decision Tree Regressor And K-Nearest Neighbors

### PR DESCRIPTION
**Pull request by vivekvardhan2810**
## 🛠️ Related Issue

Fixed: #410 

## 📝 Description

Predicting Zomato Stock Prices involves using various machine learning models like LSTM (Long Short-Term Memory), SVM (Support Vector Machine), Stochastic Gradient Descent (SGD), Decision Tree Regressor, and KNN (K-Nearest Neighbors) to analyze historical stock data and forecast future trends. Each model leverages different algorithms and methodologies to enhance prediction accuracy and reliability.

## 🔍 Type of PR

- [x] ✨ Feature enhancement
- [x] 📚 Documentation update

## ✅ Checklist

- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
Hi @Akshat111111 , Please assign labels GSSOC and level 2 to this PR.

Resolves #410

**Comment by vivekvardhan2810** [comment]
@Akshat111111 Sir

**Review by Akshat111111 — COMMENTED** [review]
work is good, but it should be inside nifty .so put entire folder under nse

**Comment by vivekvardhan2810** [comment]
Okay @Akshat111111

**Comment by vivekvardhan2810** [comment]
@Akshat111111 Can you give clarity that under which folder do i upload

**Pull request closed without merging**
