### PR TITLE
HDFC Stock Price Prediction using LSTM, K- Means Clustering And Logistic Regression

### LINKED ISSUE #438: 💡[FEATURE]: HDFC Stock Price Prediction using LSTM, K- Means Clustering And Logistic Regression
**Is your feature request related to a problem? Please describe.**
Yes, The art of forecasting stock prices has been a difficult task for many of the researchers and analysts. Investors eagerly seek effective stock price prediction systems to guide successful investments and understand future market trends.

**Describe the solution you'd like**
I would like to Add the ML Models which i am gonna build like using LSTM, K- Means Clustering And Logistic Regression using historical stock price data and relevant financial indicators, preprocess the data, performing EDA, and check the prices, and compare the model's accuracy.

**Describe alternatives you've considered**
Exploring additional models like ARIMA, XGBoost, or ensemble methods for potential improvement in forecasting accuracy.

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
## 🛠️ Related Issue

- Fixes #438 

## 📝 Description

Predicting Mastercard Stock Prices involves using various machine learning models like LSTM (Long Short-Term Memory), logistic regression and k - nearest neighbours to analyze historical stock data and forecast future trends. Each model leverages different algorithms and methodologies to enhance prediction accuracy and reliability.

## 🔍 Type of PR

- [x] 🐛 Bug fix
- [x] ✨ Feature enhancement

## ✅ Checklist

- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## ℹ️ Additional Context

[Include any additional context or information that might assist reviewers in understanding the changes]

### CODE REVIEW

**Comment by aditya-bhaumik** [comment]
@Akshat111111 please review my pull request and merge it

**Review by Akshat111111 — COMMENTED** [review]
good work, kindly correct the folder name where the spelling is wrong of analysis

**Comment by aditya-bhaumik** [comment]
@Akshat111111 please review and merge this pull request

**Review by Akshat111111 — COMMENTED** [review]
why there are 2 folders of hdfc inside nifty??

**Comment by aditya-bhaumik** [comment]
@Akshat111111 fixed it

**Comment by aditya-bhaumik** [comment]
@Akshat111111 please review the pull request now it has only one folder

**Review by Akshat111111 — COMMENTED** [review]
yeah,its fine

**Pull request merged**
