### PR TITLE
Real Estate Price Prediction Model

### PR DESCRIPTION
**Pull request by Pranshu-jais**
Created a Real Estate Price Prediction Model using ml algorithm like Random Forest,Lasso Regression etc  trained on relevant features that significantly impact real estate prices

### CODE REVIEW

**Comment by Pranshu-jais** [comment]
Created a Real Estate Price Prediction Model

**Review by Akshat111111 — COMMENTED** [review]
The model is good.Create a Mail folder with name- Hedging with Real state and It will contain Bangalore Home prices and inside it put all the 3 files.

**Comment by Pranshu-jais** [comment]
> The model is good.Create a Main folder with name- Hedging with Real state and It will contain Bangalore Home prices and inside it put all the 3 files.

I have created  a Main folder with name- Hedging with Real state and It will contain Bangalore Home prices.csv inside it and other the 2 files.

**Review by Akshat111111 — APPROVED** [review]
Now its fine.

**Comment by Pranshu-jais** [comment]
@Akshat111111  sir please  change label and add levels to count in gssoc'24

**Pull request merged**
