### PR TITLE
Hedging using knn

### PR DESCRIPTION
**Pull request by Divyanshi1002**
hey @Akshat111111 ,
please check the PR for #30 .
let me know for further alteration.

### CODE REVIEW

**Comment by Divyanshi1002** [comment]
I am new to handling financial data. Please, could you tell me how I can improve the model?

**Review by Akshat111111 — COMMENTED** [review]
Can you please put this folder inside the NSE folder

**Comment by Divyanshi1002** [comment]
@Akshat111111 , Please check i have put the folder inside Nifty folder.

**Comment by Divyanshi1002** [comment]
Hello @Akshat111111,

Could you please add the label gssoc'24 and the level2 label according to issue #30 to this PR? This would really help me gain points on the leaderboard.

Thank you for your time!

**Pull request merged**
