### PR TITLE
Enhanced Crude-oil-forecasting Model. 

### PR DESCRIPTION
**Pull request by FreeSpirit11**
In the Crude-oil-forecasting Model, I have made following changes :

1. replaced the SimpleRNN layer with LSTM layer and add return_sequences=True to the first LSTM layer to enable stacking.
2. Introduced Dropout layers after each LSTM layer to prevent overfitting.
3. experimented with different configurations of LSTM layers, including adding more layers or adjusting the number of units.

### CODE REVIEW

**Comment by FreeSpirit11** [comment]
Hi @Akshat111111 , Please assign labels GSSOC and level 2 to this PR.

Resolves #268.

**Comment by amishhaa** [comment]
Simple RNN layer had an accuracy of 96% over testing data and the mse rmse for it was <0.005 and LSTM has 93% so on what basis is this model better than the previous one? Also the plots have still not been corrected.

**Comment by amishhaa** [comment]
"Crudeoil is the target variable that we got to predict and we are going to use 6 features to do that (Gold, Silver, ChinaOilCorp, BTC(Bitcoin), Usdollar, NaturalGas)." This sentence wasn't changed as in LSTM models we only use one target feature that varies with time. 
Kindly change documentations and plots when you update existing work. Or just create a new dir. For it if you don't want to update anything and write everything from scratch 
Or the existing work gets bombarded with discrepancies.

**Comment by amishhaa** [comment]
> > "Crudeoil is the target variable that we got to predict and we are going to use 6 features to do that (Gold, Silver, ChinaOilCorp, BTC(Bitcoin), Usdollar, NaturalGas)." This sentence wasn't changed as in LSTM models we only use one target feature that varies with time. Kindly change documentations and plots when you update existing work. Or just create a new dir. For it if you don't want to update anything and write everything from scratch Or the existing work gets bombarded with discrepancies.
> 
> These people just copy other issues and raise it multiple times to get points lmao.

Don't say that as disrespecting someone is against gssoc rules the best we can do is tell @Akshat111111 about how the contributor hardly changes anything and still has gained so much points even though adding 2-3 plots should be considered level 1.

**Comment by Akshat111111** [comment]
> > > "Crudeoil is the target variable that we got to predict and we are going to use 6 features to do that (Gold, Silver, ChinaOilCorp, BTC(Bitcoin), Usdollar, NaturalGas)." This sentence wasn't changed as in LSTM models we only use one target feature that varies with time. Kindly change documentations and plots when you update existing work. Or just create a new dir. For it if you don't want to update anything and write everything from scratch Or the existing work gets bombarded with discrepancies.
> > 
> > 
> > These people just copy other issues and raise it multiple times to get points lmao.
> 
> Don't say that as disrespecting someone is against gssoc rules the best we can do is tell @Akshat111111 about how the contributor hardly changes anything and still has gained so much points even though adding 2-3 plots should be considered level 1.

I also totally agree with you and will give level 1 for such tasks

**Comment by Akshat111111** [comment]
> > > > "Crudeoil is the target variable that we got to predict and we are going to use 6 features to do that (Gold, Silver, ChinaOilCorp, BTC(Bitcoin), Usdollar, NaturalGas)." This sentence wasn't changed as in LSTM models we only use one target feature that varies with time. Kindly change documentations and plots when you update existing work. Or just create a new dir. For it if you don't want to update anything and write everything from scratch Or the existing work gets bombarded with discrepancies.
> > > 
> > > 
> > > These people just copy other issues and raise it multiple times to get points lmao.
> > 
> > 
> > Don't say that as disrespecting someone is against gssoc rules the best we can do is tell @Akshat111111 about how the contributor hardly changes anything and still has gained so much points even though adding 2-3 plots should be considered level 1.
> 
> I raised an issue and no one's looking at it

Hey Im looking into it and will do my level best

**Comment by binguliki** [comment]
> > > > > "Crudeoil is the target variable that we got to predict and we are going to use 6 features to do that (Gold, Silver, ChinaOilCorp, BTC(Bitcoin), Usdollar, NaturalGas)." This sentence wasn't changed as in LSTM models we only use one target feature that varies with time. Kindly change documentations and plots when you update existing work. Or just create a new dir. For it if you don't want to update anything and write everything from scratch Or the existing work gets bombarded with discrepancies.
> > > > 
> > > > 
> > > > These people just copy other issues and raise it multiple times to get points lmao.
> > > 
> > > 
> > > Don't say that as disrespecting someone is against gssoc rules the best we can do is tell @Akshat111111 about how the contributor hardly changes anything and still has gained so much points even though adding 2-3 plots should be considered level 1.
> > 
> > 
> > I raised an issue and no one's looking at it
> 
> Hey Im looking into it and will do my level best

Yes , Sir please  I informed you about the duplicate issues that were created but still they got merged . I hope u understand that issues should be unique.

**Comment by Akshat111111** [comment]
> > > > > > "Crudeoil is the target variable that we got to predict and we are going to use 6 features to do that (Gold, Silver, ChinaOilCorp, BTC(Bitcoin), Usdollar, NaturalGas)." This sentence wasn't changed as in LSTM models we only use one target feature that varies with time. Kindly change documentations and plots when you update existing work. Or just create a new dir. For it if you don't want to update anything and write everything from scratch Or the existing work gets bombarded with discrepancies.
> > > > > 
> > > > > 
> > > > > These people just copy other issues and raise it multiple times to get points lmao.
> > > > 
> > > > 
> > > > Don't say that as disrespecting someone is against gssoc rules the best we can do is tell @Akshat111111 about how the contributor hardly changes anything and still has gained so much points even though adding 2-3 plots should be considered level 1.
> > > 
> > > 
> > > I raised an issue and no one's looking at it
> > 
> > 
> > Hey Im looking into it and will do my level best
> 
> Yes , Sir please I informed you about the duplicate issues that were created but still they got merged . I hope u understand that issues should be unique.

yeah

**Pull request closed without merging**
