### PR TITLE
#666 Added Doge INR Analysis

### LINKED ISSUE #666: 💡[FEATURE]: Doge INR Analysis
**Is your feature request related to a problem? Please describe.**
To Analyse and predict the price of Dogecoin in the Indian Market and also in INR.

**Describe the solution you'd like**
Implement a model that includes external market factors and real-time data to improve the accuracy of Dogecoin price predictions in INR.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. Example:
- Adding additional features like trading volume, social media sentiment analysis, and market trends.
- Using more complex models such as Long Short-Term Memory (LSTM) networks for better time-series forecasting.

**Additional context**

### PR DESCRIPTION
**Pull request by priyankeshh**
## 🛠️ Related Issue

- Closes #666 

## 📝 Description

[Provide a concise description of the changes. Include the purpose and any relevant context or details.]
To Analyse and predict the price of Dogecoin in the Indian Market and also in INR.

## **Tasks Done:** ##
* Reading the data in python
* Basic Exploration of data
* Cleaning the data and transforming it to be useful for basic analysis 
* Visual Data exploration

## 🔍 Type of PR

- [ ] 🐛 Bug fix
- [ X] ✨ Feature enhancement
- [ ] 📚 Documentation update
- [ ] 🛑 Other (specify): _______________

## 📸 Screenshots / 🎥 Videos (if applicable)

[Attach screenshots or videos]

## ✅ Checklist

- [X ] I have performed a self-review of my code.
- [X ] I have read and followed the Contribution Guidelines.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## ℹ️ Additional Context

[Include any additional context or information that might assist reviewers in understanding the changes]

### CODE REVIEW

**Review by Akshat111111 — COMMENTED** [review]
kindly put inside decentralized finance folder and update the readme too

**Comment by priyankeshh** [comment]
@Akshat111111  made the required changes !
Also updated the readme.md

**Comment by priyankeshh** [comment]
@Akshat111111  can you please merge this as tomorrow is the last day of gssoc

**Review by Akshat111111 — APPROVED** [review]
fine

**Pull request merged**
