### PR TITLE
Create data_preprocessing.py

### PR DESCRIPTION
**Pull request by AKSHITHA-CHILUKA**
## 🛠️ Related Issue

- Closes #[#668]

## 📝 Description

[Provide a concise description of the changes. Include the purpose and any relevant context or details.]

## 🔍 Type of PR

- [ ] 🐛 Bug fix
- [ ] ✨ Feature enhancement
- [x] 📚 Documentation update
- [ ] 🛑 Other (specify): _______________

## 📸 Screenshots / 🎥 Videos (if applicable)

[Attach screenshots or videos]

## ✅ Checklist

- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## ℹ️ Additional Context

[Include any additional context or information that might assist reviewers in understanding the changes]

### CODE REVIEW

**Comment by AKSHITHA-CHILUKA** [comment]
#668

**Review by AKSHITHA-CHILUKA — COMMENTED** [review]
review done

**Comment by AKSHITHA-CHILUKA** [comment]
review and merge the pull request

**Review by Akshat111111 — COMMENTED** [review]
dont put directly,create a folder inside it and put your code under it

**Comment by AKSHITHA-CHILUKA** [comment]
okay

**Comment by AKSHITHA-CHILUKA** [comment]
I have added the code and requested a new pull request

**Comment by Akshat111111** [comment]
I want all the parts of sales prediction inside a single folder with 1 pull request

**Comment by AKSHITHA-CHILUKA** [comment]
okay

**Comment by AKSHITHA-CHILUKA** [comment]
should i add them in this file Store Sales Prediction

**Comment by Akshat111111** [comment]
add all the component of store sales prediction

**Comment by AKSHITHA-CHILUKA** [comment]
okay

**Pull request closed without merging**
