### PR TITLE
adding tech sector and energy sector scripts

### PR DESCRIPTION
**Pull request by michaelfred533**

### CODE REVIEW

**Comment by Akshat111111** [comment]
Thankyou so much for your time in contribution to this repository.I have merged the pull request,The results were really very intresting.

**Comment by Akshat111111** [comment]
Really the results were very fascinating.Are you on linkedin?? Lets connect on it.And What you are currently pursuing??

**Comment by michaelfred533** [comment]
I'm glad the results were interesting! I was working on testing out some stop-losses and some other things on the project recently too but haven't finished yet. But it's very interesting! I am on linkedin I'll add you there! Recently I was working in user research and data analysis

**Comment by michaelfred533** [comment]
Can you send me a link to your linkedin?

**Comment by Akshat111111** [comment]
https://www.linkedin.com/in/akshat-sharma-638b16219/

**Pull request merged**
