### PR TITLE
Solved #442- Proximity to POI

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
## 🛠️ Related Issue

- Closes #[issue_number]
- #442 

## 📝 Description

[Provide a concise description of the changes. Include the purpose and any relevant context or details.]

## 🔍 Type of PR

- [ ] 🐛 Bug fix
- [x] ✨ Feature enhancement
- [ ] 📚 Documentation update
- [ ] 🛑 Other (specify): _______________

## 📸 Screenshots / 🎥 Videos (if applicable)

[Attach screenshots or videos]

## ✅ Checklist

- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## ℹ️ Additional Context

[Include any additional context or information that might assist reviewers in understanding the changes]

### CODE REVIEW

**Comment by Aditi22Bansal** [comment]
@Akshat111111 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@Akshat111111 
Kindly review

**Comment by Aditi22Bansal** [comment]
@Akshat111111 
Kindly review and merge the PR

**Review by Akshat111111 — COMMENTED** [review]
kindly put your entire folder inside financial domain

**Pull request closed without merging**
