### PR TITLE
added contributors info in  README.md

### PR DESCRIPTION
**Pull request by misskiran**
I have added the contributor list consisting of their names and github profile links.Pls Check.

### CODE REVIEW

**Review by Akshat111111 — APPROVED** [review]
Done.

**Comment by Akshat111111** [comment]
Kindly resolve the conflict so that I will merge it.

**Comment by misskiran** [comment]
I have resolved them now.

**Comment by misskiran** [comment]
You do want me to keep updating the Contributor list?

**Comment by Akshat111111** [comment]
> You do want me to keep updating the Contributor list?

Yes this should also be done.Create a new issue for it and do it.

**Comment by misskiran** [comment]
Okay , I will update the contributor list in every  24hours if there are new contributors by raising an issue.

**Comment by Akshat111111** [comment]
sure

**Pull request merged**
