### PR TITLE
Evaluation metrices RMSE, MSE and MAE #22

### PR DESCRIPTION
**Pull request by apooyadv**
I've created a model and evaluated it on various metrics.

### CODE REVIEW

**Review by Akshat111111 — COMMENTED** [review]
You can further improve this credit risk code by adding more models

**Comment by apooyadv** [comment]
done, you can merge this.

**Review by Akshat111111 — APPROVED** [review]
Now its work well

**Comment by Akshat111111** [comment]
The random walk file is not opening ?? Kindly make it as per the notebook standards

**Comment by apooyadv** [comment]
> The random walk file is not opening ?? Kindly make it as per the notebook standards

Done.

**Pull request merged**
