### PR TITLE
Added workflow for closing old issues

### LINKED ISSUE #135: Adding Workflow for Closing Old Issues
Over time, repositories can accumulate a large number of open issues, including some that may no longer be relevant or actively worked on. Manually closing these old issues can be time-consuming and tedious.
I would like to add a workflow that automatically identifies and closes old issues based on certain criteria, such as no recent activity or being open for a specific duration.

### PR DESCRIPTION
**Pull request by Asymtode712**
Fixes #135 

@Akshat111111 please review this PR and merge it if it is good to go

### CODE REVIEW

**Comment by Akshat111111** [comment]
Kindly add a description file too with your current file explaining when your issue will be closed, so new contributors will not panic.

**Comment by Asymtode712** [comment]
@Akshat111111 Implemented your suggestion, kindly check the latest commit and merge it if it is good to go

**Review by Akshat111111 — APPROVED** [review]
Yeah, now its fine.

**Comment by Asymtode712** [comment]
@Akshat111111 i guess you forgot to label it while merging with 'gssoc' and relevant level labels😅. Please label it.

**Comment by Asymtode712** [comment]
@Akshat111111 i guess you forgot to label it while merging with 'gssoc' and relevant level labels😅. Please label it.

**Comment by Asymtode712** [comment]
please change the 'level2' label to 'level1' label as per instructions which you might have recieved

**Pull request merged**
