### PR TITLE
HCLtech stock price prediction using Linear Regression, Support Vector Machines (SVM)

### LINKED ISSUE #445: 💡[FEATURE]: HCLtech stock price prediction using Linear Regression, Support Vector Machines (SVM) and K means clustering
**Is your feature request related to a problem? Please describe.**
Yes, The art of forecasting stock prices has been a difficult task for many of the researchers and analysts. Investors eagerly seek effective stock price prediction systems to guide successful investments and understand future market trends.

**Describe the solution you'd like**
I would like to Add the ML Models which i am gonna build like using linear regression, support vector machines and  K- Means Clustering And Logistic Regression using historical stock price data and relevant financial indicators, preprocess the data, performing EDA, and check the prices, and compare the model's accuracy.

**Describe alternatives you've considered**
Exploring additional models like ARIMA, XGBoost, or ensemble methods for potential improvement in forecasting accuracy.

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
## 🛠️ Related Issue

- Closes #445 

## 📝 Description

[Provide a concise description of the changes. Include the purpose and any relevant context or details.]

Predicting HCLTech Stock Prices involves using various machine learning models like Linear Regression, SVM and k - nearest neighbours to analyze historical stock data and forecast future trends. Each model leverages different algorithms and methodologies to enhance prediction accuracy and reliability.

## 🔍 Type of PR

- [x] 🐛 Bug fix
- [x] ✨ Feature enhancement

## ✅ Checklist

- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

@Akshat111111 please review this pull request and merge this under gssoc'24

### CODE REVIEW

**Review by Akshat111111 — COMMENTED** [review]
you have putted hdfc inside hcl tech?? And hdfc work has been already done

**Comment by aditya-bhaumik** [comment]
@Akshat111111 hi i have added the correct model actually i had saved both of this code together then put it in different folders i by mistake put the hdfc in both the folders

**Comment by aditya-bhaumik** [comment]
@Akshat111111 i checked the images and dataset they are of hcltech only only the model i had made mistake

**Review by Akshat111111 — COMMENTED** [review]
yeah, now its fine

**Pull request merged**
