### PR TITLE
#665 Added ASELSAN Stock Price Prediction

### LINKED ISSUE #665: 💡[FEATURE]: ASELSAN Stock Price Prediction
**Is your feature request related to a problem? Please describe.**
This project involves the analysis and prediction of ASELSAN stock prices using historical stock price data from 2017 to 2022. The aim is to create an accurate predictive model by exploring the dataset, visualizing different aspects of the stock prices, and implementing various machine learning algorithms.

**Describe the solution you'd like**
Implement a more robust model that includes external market indicators and news sentiment analysis to improve prediction accuracy.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by priyankeshh**
## 🛠️ Related Issue

- Closes #665 

## 📝 Description

[Provide a concise description of the changes. Include the purpose and any relevant context or details.]
This project involves the analysis and prediction of ASELSAN stock prices using historical stock price data from 2017 to 2022. The aim is to create an accurate predictive model by exploring the dataset, visualizing different aspects of the stock prices, and implementing various machine learning algorithms.

### 🧮 **What I Had Done!**

1. **Data Preprocessing**:
   - Imported necessary libraries and the dataset.
   - Deleted unnecessary columns to streamline the dataset.
   - Changed data types of relevant columns for accurate analysis.

2. **Exploratory Data Analysis and Visualization**:
   - Conducted exploratory data analysis (EDA) to understand the dataset.
   - Visualized different aspects of the dataset using plots and charts:
     - **Variation of Opening Price**: Plotted the variation of ASELSAN's opening price over time.
     - **Heatmap**: Created a heatmap to understand correlations between features.
     - **Closing Price Trends**: Analyzed trends in closing prices over the years.
     - **Volume Traded**: Visualized the volume of stocks traded over time.
     - **Price Distribution**: Examined the distribution of stock prices.
     - **Daily Returns**: Plotted daily returns to understand stock volatility.
     - **Yearly Trends**: Investigated yearly trends in stock prices.
     - **Correlation Matrix**: Displayed the correlation matrix to find relationships between variables.

3. **Model Development**:
   - Developed and applied various machine learning models for predicting ASELSAN stock prices.
   - Evaluated the performance of each model using appropriate metrics.

### 🚀 **Models Implemented**

- **Linear Regression**: Chosen for its simplicity and interpretability.
- **Lasso Regression**: Selected to prevent overfitting by adding L1 regularization.
- **Ridge Regression**: Utilized for L2 regularization, although it performed poorly.
- **Decision Tree Regressor**: Selected for its ability to model non-linear relationships.

## 🔍 Type of PR

- [ ] 🐛 Bug fix
- [X ] ✨ Feature enhancement
- [ ] 📚 Documentation update
- [ ] 🛑 Other (specify): _______________

## 📸 Screenshots / 🎥 Videos (if applicable)

[Attach screenshots or videos]

## ✅ Checklist

- [ X] I have performed a self-review of my code.
- [ X] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.

## ℹ️ Additional Context

[Include any additional context or information that might assist reviewers in understanding the changes]

### CODE REVIEW

**Review by Akshat111111 — COMMENTED** [review]
put your folder inside NYSE

**Comment by priyankeshh** [comment]
@Akshat111111  done !

**Comment by priyankeshh** [comment]
@Akshat111111  can you please merge this as tomorrow is the last day of gssoc

**Review by Akshat111111 — APPROVED** [review]
fine

**Pull request merged**
