### PR TITLE
here is my Finacial stats by using HTML

### PR DESCRIPTION
**Pull request by PRIYANSHU2026**

### CODE REVIEW

**Review by Akshat111111 — COMMENTED** [review]
The html button is not working, and dont put the amazon, msft.......  inside nifty

**Comment by PRIYANSHU2026** [comment]
done sir

**Review by Akshat111111 — COMMENTED** [review]
yeah, its perfect.Kindly add the reference that you have gone through in kaggle

**Comment by Akshat111111** [comment]
There is also a conflict so remove it

**Comment by PRIYANSHU2026** [comment]
sure sir

**Review by Akshat111111 — COMMENTED** [review]
still there is a conflict

**Review by Akshat111111 — COMMENTED** [review]
yeah, it works

**Comment by Akshat111111** [comment]
but remove the conflict and make a new pr

**Pull request closed without merging**
