### PR TITLE
Daily News and Stock Data Analysis

### LINKED ISSUE #286: 💡[FEATURE]: Daily News and Stock Data Analysis (Data set Originally prepared for a deep learning and NLP class, this dataset was meant to be used for a binary classification task)
Originally prepared for a deep learning and NLP class, this dataset was meant to be used for a binary classification task. News and Stock Data includes historical news headlines crawled from Reddit’s r/worldnews subreddit from June 8th, 2008 to July 1st, 2016. Additionally, it includes Dow Jones Industrial Average data from August 8th, 2008 to July 1st, 2016.
https://www.kaggle.com/aaron7sun/stocknews

Can you assign it to me? @Akshat111111

Full name: Manish Rana
GitHub profile link: https://github.com/ranamanish674zu
Email ID: [manish.rana2021@vitbhopal.ac.in](mailto:manish.rana2021@vitbhopal.ac.in)
Approach for this project: Will use Deep Learning algorithm and python
What is your participant role?: GSSoC-2024 contributor

Can you add the label for GSSoC, i want to work on it
Thanks.

### PR DESCRIPTION
**Pull request by ranamanish674zu**
## 🛠️ Related Issue

- Closes #286 
- Fixes #286 
- Resolves #286 

## 📝 Description
Originally prepared for a deep learning and NLP class, this dataset was meant to be used for a binary classification task. News and Stock Data includes historical news headlines crawled from Reddit’s r/worldnews subreddit from June 8th, 2008 to July 1st, 2016. Additionally, it includes Dow Jones Industrial Average data from August 8th, 2008 to July 1st, 2016.
https://www.kaggle.com/aaron7sun/stocknews

## 🔍 Type of PR

- [ ] 🐛 Bug fix
- [+] ✨ Feature enhancement
- [ ] 📚 Documentation update
- [ ] 🛑 Other (specify): _______________

## 📸 Screenshots / 🎥 Videos (if applicable)

[Attach screenshots or videos]
here are some screenshot ->
image
image
## ✅ Checklist

- [X ] I have performed a self-review of my code.
- [ X] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have commented my code, particularly in hard-to-understand areas.

## ℹ️ Additional Context

[Include any additional context or information that might assist reviewers in understanding the changes]
Thank you so much 
@Akshat111111 complete #286 could you please review

### CODE REVIEW

**Review by Akshat111111 — COMMENTED** [review]
kindly put your Stock market prediction folder  inside NYSE and name it as Google advanced analysis

**Review by Akshat111111 — COMMENTED** [review]
And put the daily news folder inside the financial domain folder.

**Comment by ranamanish674zu** [comment]
@Akshat111111  sir due to some issue i am making the new PR with desire changes whch you told

**Comment by Akshat111111** [comment]
okay

**Pull request closed without merging**
