### PR TITLE
Loan interest rate prediction using machine learning

### LINKED ISSUE #479: 💡[FEATURE]: Loan interest rate prediction using machine learning
**Is your feature request related to a problem? Please describe.**

This project aims to predict the rate of interest on loans that  is taken by various organizations and bank by taking inputs from user like loan amount , financial status , number of years employed, home ownership , annual income , purpose of loan , dept to income ratio, gender ,occupation , total accounts and assets etc using machine learning techniques.

i will develop a Streamlit application for my prediction , graphical analysis and insights as like my previous works like data scraper, car ownership ,credit score classification and salary prediction.

**Describe the solution you'd like**
I will train the machine learning model on given Kaggle dataset of JanataHack :
https://www.kaggle.com/datasets/shravankoninti/janatahack-machine-learning-for-banking?select=train_fNxu4vz.csv

i will also do a complete data analysis and EDA, comparison between various algorithms and write my all setup and work under readme.md

**Additional context**
none

### PR DESCRIPTION
**Pull request by RajKhanke**
## 🛠️ Related Issue

- closes #479 

## 📝 Description

This project involves developing a Streamlit application for predicting loan interest rates based on user-provided inputs. The application utilizes a trained XGBoost machine learning model loaded from a saved file (xgboost_model.pkl). Users input various factors such as loan amount, work experience, home ownership status, income verification, purpose of loan, gender, annual income, debt-to-income ratio, and other financial metrics. The input data undergoes preprocessing using LabelEncoder to transform categorical variables into numerical values suitable for model prediction. Upon clicking the prediction button, the application displays the estimated loan interest rate in a styled success box with a green background, white bold text, and bordered layout. This project integrates basic CSS styling within Streamlit's Markdown functionality to enhance the visual presentation of the prediction results, aiming for a user-friendly and informative interface for loan interest rate prediction.

models used :
Xgboost , Gbm ,linear regression , random forest

## 🔍 Type of PR

- [ ] 🐛 Bug fix
- [X] ✨ Feature enhancement
- [ ] 📚 Documentation update
- [ ] 🛑 Other (specify): _______________

## 📸 Screenshots / 🎥 Videos (if applicable)

https://github.com/user-attachments/assets/4c8a93f5-af4b-47dc-bdfa-7b8ecc783894

## ✅ Checklist

- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by RajKhanke** [comment]
@Akshat111111  please look forwards towards this PR

**Comment by RajKhanke** [comment]
@Akshat111111 please look forward towards my this PR as well as salary prediction and diamond price prediction

**Review by Akshat111111 — COMMENTED** [review]
put it inside already existing loan folder

**Comment by RajKhanke** [comment]
@Akshat111111 now i have done the updated changes please merge it along with level and label , also please look forward towards salary prediction and restaurant revenue prediction PR

**Review by Akshat111111 — COMMENTED** [review]
yeah,good work

**Pull request merged**
