### PR TITLE
here is my upgrade version of nifty analysis

### PR DESCRIPTION
**Pull request by PRIYANSHU2026**

### CODE REVIEW

**Review by Akshat111111 — COMMENTED** [review]
Why have you putted that Ds_store inside NYSE ?? as well as in the main folder?

**Comment by PRIYANSHU2026** [comment]
sir this the upgraded version of nifty by using rnn so thats why i puuted in nifty folder

**Review by Akshat111111 — COMMENTED** [review]
why you are putting DS_store inside NYSE ??

**Comment by PRIYANSHU2026** [comment]
sir gait se hoagy hai ap what se remove kardo please

**Comment by Akshat111111** [comment]
> sir gait se hoagy hai ap what se remove kardo please

create a new PR

**Comment by PRIYANSHU2026** [comment]
ok sir

**Pull request closed without merging**
