### PR TITLE
Added GDP prediction

### LINKED ISSUE #500: 💡[FEATURE]: Add GDP Prediction Model
**Is your feature request related to a problem? Please describe.**
Yes, the current challenge is accurately predicting the Gross Domestic Product (GDP) using available economic and financial data. Existing models may not adequately capture all the necessary variables, leading to less accurate forecasts, which in turn affects economic planning and decision-making.

**Describe the solution you'd like**
I would like to develop an advanced GDP prediction model that incorporates a wider range of economic indicators, such as consumer spending, business investment, government spending, net exports, and other relevant financial metrics. This model should use sophisticated machine learning techniques to improve prediction accuracy and provide more reliable forecasts. By doing so, it will assist policymakers, investors, and businesses in making more informed decisions based on a comprehensive analysis of economic trends.

### PR DESCRIPTION
**Pull request by pavitraag**
## 🛠️ Related Issue
Added GDP Prediction

Closes #500 

## 🔍 Type of PR

- [ ] 🐛 Bug fix
- [X] ✨ Feature enhancement
- [ ] 📚 Documentation update
- [ ] 🛑 Other (specify): _______________

## ✅ Checklist

- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by Akshat111111 — COMMENTED** [review]
put it inside financial domain folder

**Comment by pavitraag** [comment]
@Akshat111111 done with the changes

**Comment by pavitraag** [comment]
@Akshat111111 done with changes

**Review by Akshat111111 — COMMENTED** [review]
yeah, it works

**Pull request merged**
