### PR TITLE
Improved the GDP growth prediction model

### LINKED ISSUE #95: Enhance GDP Growth Prediction Model Interpretability and Visualization
**Description:**
The current implementation of the growth prediction model lacks sufficient visualizations and interpretability features, limiting its ability to provide comprehensive insights into the relationship between market capital and GDP growth. To improve the user experience and facilitate better understanding, we propose enhancing the model with additional visualizations and interpretability tools.

**Proposed Changes:**
1. **Feature Importance Plot:** Generate a feature importance plot to visualize the relative importance of each feature (percentage change in market capital) in predicting GDP growth. This will help users understand which factors have the most significant impact on GDP.
   
2. **Residual Plot:** Plot the residuals (differences between actual and predicted GDP values) to assess the goodness-of-fit of the model and identify any systematic errors or patterns.

3. **Time Series Decomposition:** Decompose the GDP time series data into trend, seasonal, and residual components to uncover underlying patterns and seasonal fluctuations in GDP growth.

4. **Correlation Heatmap:** Create a heatmap to visualize the correlation between GDP growth and other economic indicators or macroeconomic variables, providing insights into potential relationships and dependencies.

5. **Interactive Plots:** Implement interactive visualization libraries like Plotly or Bokeh to create dynamic and interactive plots, allowing users to explore the data dynamically and interact with specific data points.

6. **Model Performance Metrics:** Display performance metrics such as Mean Absolute Error (MAE), Mean Squared Error (MSE), and R-squared (R2) score to quantify the accuracy and performance of the regression model.

**Benefits:**
- Improved model interpretability and insightfulness.
- Enhanced user experience through interactive visualization.
- Better understanding of the relationship between market capital and GDP growth.
- Quantitative assessment of model performance using performance metrics.

### PR DESCRIPTION
**Pull request by FreeSpirit11**
Implemented residual plot, time series decomposition, correlation heatmap, interactive plots, and model performance metrics to provide comprehensive insights into the relationship between market capital and GDP growth.

Resolves #95

### CODE REVIEW

**Comment by amishhaa** [comment]
Your plots for 'GDP and Market Capital Percentage Change Over Time' and 'Gdp Growth Trends By country' is blank if you intend to keep those plots in your PR dont change the original code as it works fine.
Secondly, the model that you have deployed is not really the best choice as the R^2 is < 0.05  and mse>40 ACCURATE GDP predictions need more parameters than just the capital of country.(like stocks gold etc.)
Can you give some explanations in the notebook that what do we decipher from the model's predictions and heatmaps that you have deployed?

**Comment by FreeSpirit11** [comment]
I see, the new models do not significantly improve the accuracy or performance of the project as intended. I apologize for any inconvenience caused by generating the pull request prematurely. Moving forward, I will focus on other issues within the project that have more potential for improvement. Thank you for your understanding.

**Comment by Akshat111111** [comment]
> Your plots for 'GDP and Market Capital Percentage Change Over Time' and 'Gdp Growth Trends By country' is blank if you intend to keep those plots in your PR dont change the original code as it works fine. Secondly, the model that you have deployed is not really the best choice as the R^2 is < 0.05 and mse>40 ACCURATE GDP predictions need more parameters than just the capital of country.(like stocks gold etc.) Can you give some explanations in the notebook that what do we decipher from the model's predictions and heatmaps that you have deployed?

Thankyou for your suggestions

**Comment by FreeSpirit11** [comment]
Hi  @Akshat111111 , Please assign labels **GSSOC**  and **level 2** to this PR else it wont update in Leader board as mentioned in latest GSSOC guidelines.

**Pull request closed without merging**
