### PR TITLE
Added salary prediction using Machine learning

### LINKED ISSUE #413: 💡[FEATURE]:  Salary prediction using Machine learning
**Is your feature request related to a problem? Please describe.**

Salary , Revenue and taxes are important part of Indian financial system. Salary prediction project predicts the salary of an individual based on various inputs like age, gender , occupation ,  Job Title, Year of Experience , Salary etc.

It will also give an idea of which factors affect the salary of individuals based on their education level and job.

**Describe the solution you'd like**
I will train the machine learning model from the below dataset :-
https://www.kaggle.com/datasets/rkiattisak/salaly-prediction-for-beginer/data

I will compare the strength of models like linear regression ,random forest etc , do a complete data analysis and perform EDA. I wll also prepare readme.md file.

**Additional context**
None

### PR DESCRIPTION
**Pull request by RajKhanke**
- Closes #413 

## 📝 Description

The salary prediction project utilizes machine learning models to forecast salaries based on various input parameters such as age, gender, education level, job title, and years of experience. The goal is to provide users with accurate salary estimates derived from a trained predictive model.

The below csv dataset from kaggle is used as reference which contains nearly 300+ rows (salary_prediction.ipynb) on which processing is performed to obtained a  processed data , all this processing is performed in first notebook (salary-prediction.ipynb) file.

The dataset link is are as follows :-
https://www.kaggle.com/datasets/rkiattisak/salaly-prediction-for-beginer

on this dataset, below processing are performed :
1) feature scaling and column reinitialization
2) errors and outliers removal using box plot
3) remove na, missing values , regularization etc
4) Drop duplicates , normalization , column dropping

(all this works are depicted in salary_prediction file)

The model is trained on processed data after data processing and feature engineering  and all works associated with it are depicted in salary_prediction.ipynb file.

Methodology: 
1. **Data Preprocessing and feature engineering**

2. **Exploratory Data Analysis (EDA)**:
    after Data preprocessing the next step is Exploratory  data analysis using different plotting libraries like matplotlib, pandas, seaborn and plotly. following plots were plotted in this step:-
    1) Pie charts
    2) violin plots
    3) box plot of numerical features
    4) count plots
    5) histogram
    6) model comparison graphs
    7) Actual vs predicted regression lines
    (refer images folder for this images and graph observation)

     The four machine learning model random forest , XGBoost ,multiple linear regression, gradient boosting machine are selected for model training over the inputted processed data:
     random forest accuracy : 90 %
     GBM accuracy : 91 %
     XGBOOST accuracy : 92 %
     Multiple linear regression accuracy : 89 %

     The 10 fold cross validation is then performed on XGBOOST model to obtained a final average cross validated accuracy of 86 % .

     This  XGBOOST model is then loaded into Streamlit application after installing and using Joblib library.

## 🔍 Type of PR

- [X] ✨ Feature enhancement

## 📸 Screenshots / 🎥 Videos (if applicable)

https://github.com/user-attachments/assets/633f2f42-d3db-4cf6-89ee-79b679debd05

## ✅ Checklist

- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by RajKhanke** [comment]
@Akshat111111 please merge this PR along with gssoc'24 label and level (3), This will resolve issue no. 413

**Comment by RajKhanke** [comment]
@Akshat111111 please look towards this PR

**Comment by RajKhanke** [comment]
@Akshat111111 please look forwards towards this PR

**Review by Akshat111111 — COMMENTED** [review]
good work,Put your folder inside loan status prediction

**Comment by RajKhanke** [comment]
@Akshat111111 now i have put it under loan status  prediction , please now merge it along with level and label of gssoc'24. also please look towards my other pr's of loan interest rate prediction and restaurant revenue prediction.

**Pull request merged**
