### PR TITLE
Added Advanced Visualizations to forex model

### PR DESCRIPTION
**Pull request by FreeSpirit11**
I have added following visualisations to forex model("Hedging-of-Financial-Derivatives/forex /forex.ipynb").

1.Visualize Training and Validation Losses
2.Visualize Predictions vs. Actual Values
3.Detailed Comparison of Predictions
4.Error Analysis
5.Distribution of Errors
6.Interactive Visualizations

### CODE REVIEW

**Comment by FreeSpirit11** [comment]
Hi @Akshat111111 , Please assign labels GSSOC and level 3 to this PR else it wont update in Leader board as mentioned in latest GSSOC guidelines.

Resolves #200.

**Review by Akshat111111 — APPROVED** [review]
yeah, it works

**Comment by amishhaa** [comment]
The model is so poorly documented the contributor hasn't even written the Title of the model in the work.

No documentation comments etc.are included for anything in this work. I needed to look at the data headers closely to figure out what  this model is trying to predict. Documentation is really important so people who are going to be working on this project after you knows what is and is not implemented or what this model does or does not do currently.

A model for exchange rate prediction already exists the only new feature implemented by this model is using yahoof api for live predictions which could have been implemented on the original model itself or atleast this could be moved to the dir. that contains the original model for exchange predictions so that everything is organised.

Also if I am understanding the goal of this work correctly it was to predict forex but nowhere in the work is predicted forex returned as a value(this would involve converting the data to original value as you have used min max scaler and then output that as the predicted value)

Hope @Akshat111111 acknowledges.
@FreeSpirit11 you can always go through other works of this repo to familiarise yourself with the documentation and discription standards of this project. And I have noticed the corrections discussed for crude oil forecasting have still not been implemented if you're facing any difficulties doing that feel free to contact the mentors :)

**Comment by Akshat111111** [comment]
> The model is so poorly documented the contributor hasn't even written the Title of the model in the work.
> 
> No documentation comments etc.are included for anything in this work. I needed to look at the data headers closely to figure out what this model is trying to predict. Documentation is really important so people who are going to be working on this project after you knows what is and is not implemented or what this model does or does not do currently.
> 
> A model for exchange rate prediction already exists the only new feature implemented by this model is using yahoof api for live predictions which could have been implemented on the original model itself or atleast this could be moved to the dir. that contains the original model for exchange predictions so that everything is organised.
> 
> Also if I am understanding the goal of this work correctly it was to predict forex but nowhere in the work is predicted forex returned as a value(this would involve converting the data to original value as you have used min max scaler and then output that as the predicted value)
> 
> Hope @Akshat111111 acknowledges. @FreeSpirit11 you can always go through other works of this repo to familiarise yourself with the documentation and discription standards of this project. And I have noticed the corrections discussed for crude oil forecasting have still not been implemented if you're facing any difficulties doing that feel free to contact the mentors :)

Thankyou for guiding @FreeSpirit11 .I hope she will update it too by making a new PR

**Comment by FreeSpirit11** [comment]
Hi @Akshat111111, I have added advanced visualizations as outlined in issue #200. You may proceed to close this issue. I will create a new issue to address the changes suggested by amishaa.

**Comment by Akshat111111** [comment]
> Hi @Akshat111111, I have added advanced visualizations as outlined in issue #200. You may proceed to close this issue. I will create a new issue to address the changes suggested by amishaa.

okay

**Comment by amishhaa** [comment]
Why is this assigned a level 3 ?

**Comment by Akshat111111** [comment]
> Why is this assigned a level 3 ?

Its by mistake.Now I have updated it.

**Pull request merged**
