### PR TITLE
Added more visualisations to Exchange Traded Funds project

### LINKED ISSUE #122: Add more visualisations to Exchange Traded Funds project.
To further enrich the script's capabilities and improve its usefulness, I propose the addition of more visualizations to (Hedging-of-Financial-Derivatives/Exchange Traded Funds /ETFs.ipynb).

### PR DESCRIPTION
**Pull request by FreeSpirit11**
The new code includes additional visualizations such as a cumulative explained variance plot for PCA components and an elbow plot for determining the optimal number of clusters for KMeans clustering. 

Resolves #122

### CODE REVIEW

**Review by Akshat111111 — COMMENTED** [review]
you have removed a lot of existing code that might be helpful for the beginners, so add your code in such a manner so it will not affect the existing code.

**Comment by FreeSpirit11** [comment]
Okay, I will create another pull request for that.

**Review by Akshat111111 — APPROVED** [review]
yeah, now its fine.

**Comment by FreeSpirit11** [comment]
Hi  @Akshat111111 , Please assign labels **GSSOC**  and **level 2** to this PR else it wont update in Leader board as mentioned in latest GSSOC guidelines.

**Pull request merged**
